version: '3.1'

services: 
  keycloak:
    image: jboss/keycloak:15.0.0
    container_name: keycloak
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
      DB_VENDOR: mysql
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_IMPORT: /tmp/import-frontend.json
    ports:
      - 38080:8080
    volumes:
      - ./keycloak/import-frontend.json:/tmp/import-frontend.json
    depends_on:
      - mysql
  mysql:
    image: mysql/mysql-server:8.0.27-1.2.5-server
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
    - 3306:3306
  root-app:
    build: ./root-app
    ports:
      - 3100:3100
  second-app:
    build: ./second-app
    ports:
      - 4100:4100
  third-app:
    build: ./third-app
    ports:
      - 5101:5101