apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: masemfordev-com
  namespace: frontend
spec:
  secretName: masemfordev-com-tls
  duration: 2160h
  renewBefore: 360h
  #organization:
  #  - masemfordev
  commonName: "*.masemfordev.com"
  isCA: false
  #keySize: 2048
  #keyAlgorithm: rsa
  #keyEncoding: pkcs1
  usages:
    - server auth
    - client auth
  dnsNames:
    - masemfordev.com
    - "*.masemfordev.com"
  # Issuer references are always required.
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer